# Generated by Django 4.0.4 on 2022-05-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_remove_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(null=True, upload_to='course_images/'),
        ),
    ]
