# Generated by Django 4.0.4 on 2022-05-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_enrolled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='reading_content',
            field=models.FileField(null=True, upload_to='course_reading_content_uploaded'),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
